### ISSUE TITLE
和gitbook自带的plugin-fontsettings有冲突

### ISSUE THREAD

**Issue by tankilo** [lwdgit/gitbook-plugin-search-plus#1]
和gitbook自带的plugin-fontsettings有冲突，这个用上以后，plugin-fontsetting按钮就没了
用的GitBook 3.2.2

**Comment by lwdgit** [comment]
@tankilo fontsetting的按钮还在，只是被滚动到上面了，你需要往回滚动一下才能看到。另外，我将search-plus去掉后这个问题依然是存在的。
