### ISSUE TITLE
Bug: search hit not highlighted if search phrase contains tags

### ISSUE THREAD

**Issue by nagim** [lwdgit/gitbook-plugin-search-plus#2]
Hi,

This plugin is so great, thanks for it!

I've encountered one bug: if the search phrase is mixed format (like text and `<span>`, text and `<code>`, for example: "set to `false`"), it will appear in the search hit list, but highlighting won't work.
Console output:
```
Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined
    at search.js:185
```

It seems like the regex (`RegExp('(>[^<]*)(' + escapeReg(keyword) + ')', 'igm')`) in the search.js won't match those terms, where in the html, there's another tag inside the `<p>` tag (like `<p>init-<span class="message">SUBSCRIBE</span></p>`), so highlighting fails, because no `search-highlight` class is applied to them.

Could you please look into this?

Thanks in advance!

Cheers,
Imre

**Comment by lwdgit** [comment]
The *highlight plugin* will change the element struct, and I will to resolve it. Thanks for reply

**Comment by lwdgit** [comment]
@nagim ，bug has fixed.  You can test it by `npm install gitbook-plugin-search-plus@0.0.10`.

Here is example:  https://lwdgit.github.io/gitbook-plugin-search-plus/book/Introduction-to-Webpack.html?h=require(%27gulp%27)

**Comment by nagim** [comment]
That's really great, thank you very much for the quick fix!
I'm closing the issue.
