### ISSUE TITLE
Cannot read property 'getEngine' of undefined

### ISSUE THREAD

**Issue by hhkaos** [lwdgit/gitbook-plugin-search-plus#3]
Do you know why I'm receiving this error? [here](https://hhkaos.github.io/awesome-arcgis/)

I'm using:
> **GitBook version**: 3.2.2
**OS X Yosemite** (10.10.5)
**Tested in**: Chrome 55.0.2883.95 (64-bit), Firefox (50.0) & Safari (10.0.2)

Thanks in advance

**Comment by lwdgit** [comment]
Error comes from **gitbook-plugin-lunr**, you can disable this plugin too！ like this:
```
{
    "plugins": ["-lunr","-search","search-plus"]
}
```

https://lwdgit.github.io/gitbook-plugin-search-plus/book.js

**Comment by hhkaos** [comment]
Thanks! solved :dancer:
