### ISSUE TITLE
issue with toggle-chapters

### ISSUE THREAD

**Issue by nagim** [lwdgit/gitbook-plugin-search-plus#4]
Hi,

I'm using empty chapters in my book with the ungrey and toggle-chapters plugin. This allows to display only the top level articles in the ToC at startup, then expand the child articles by clicking on the main article.

However, if I'm using the search plugin, the whole ToC structure is expanded on startup and will only fold back if I refresh.

Could you please check if you could solve this problem?

Many thanks!

**Comment by lwdgit** [comment]
can you show me a example?

**Comment by nagim** [comment]
Hi,

It occurred with the older version, where `lunr` is enabled.
In the newer version, where `lunr` has to be disabled, it works correctly.

I will test search accuracy (as disabling `lunr` makes us rely on the `search_plus_index.json` only), if it's good, I will close the issue.

Thanks!

**Comment by nagim** [comment]
I'm closing this since the search accuracy seems to be good and the issue is gone.

Thanks!
