### ISSUE TITLE
short description truncate at word limit

### ISSUE THREAD

**Issue by nagim** [lwdgit/gitbook-plugin-search-plus#6]
Hi,

In the search result list, there is a short text from the chapter, which is truncated at max. 50 characters before the first hit. It's good, but it often cuts off the text in the middle of a word.
It would look much better, if it would cut off the text at word boundaries, or, for example would return the whole paragraph in which the hit is located.

Thanks!

**Comment by lwdgit** [comment]
Please use version 0.0.11. Just by excute `npm install gitbook-plugin-search-plus@0.0.11`

**Comment by nagim** [comment]
Thank you very much, I will test it soon!
